### ISSUE TITLE
EMSRProto-2 NeutronFcF435Aio 默认开启X8支持

### ISSUE THREAD

**Issue by shanggl** [flightng/atbetaflight#15]
### Is your feature request related to a problem? Please describe

当前两个版本飞控支持飞控，但是前期设计中配置了4个舵机，部分用户在使用中需要手工调整Resource映射不够方便

### Describe the solution you'd like

改为默认开启8个Motor，

### Describe alternatives you've considered

如果需要启用Servo 提供手工方式

**Comment by DusKing1** [comment]
将默认配置从4电机+4舵机改为8电机+0舵机确实可以更符合更多数用户的使用习惯，但默认开启x8就没必要了吧。

**Comment by shanggl** [comment]
修改为默认 8电机 ，默认不开x8模式
