### ISSUE TITLE
Support for AT32F435VGT7 

### ISSUE THREAD

**Issue by rajnish22-glitch** [flightng/atbetaflight#43]
### Is your feature request related to a problem? Please describe

Hi i wonder if the firmware is only limited to AT32F435VMT7 or VGT7 can be also used for the same firmware

### Describe the solution you'd like

If AT32F435VGT7 could be also added that would be great 

### Describe alternatives you've considered

havent considered any alternatevies yet

**Comment by DusKing1** [comment]
https://github.com/flightng/atbetaflight/blob/4.3-bsp-rebase/src/main/target/NEUTRONRCF435SE/target.mk#L2-L2

**Comment by cboma1986** [comment]
Стек BLITZ ATF435 (E55S 4-в-1 ESC)
дайте пожалуйста ссылку на .hex
слетела прошивка полётного контроллера
