### ISSUE TITLE
HD Canvas mode

### ISSUE THREAD

**Issue by oldrootbeer** [flightng/atbetaflight#60]
### Is your feature request related to a problem? Please describe

Hi. I have no osd on a walksnail system using uart 2 of neutronrc at32f435 mini aio.
I have inputted the correct cli commands.

### Describe the solution you'd like

hd canvas support

### Describe alternatives you've considered

Dumping the neutronrc at32f435 mini aio

**Comment by shanggl** [comment]
branch  add_osd_hd_support has support HD canvas mode ,you can make a test

**Comment by oldrootbeer** [comment]
Edit... My tbs xfire nano tx/rx were miswired on uart 5. I corrected this and the osd appeared.
